# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:            'Dear Future Self'
tagline:          'Have you already forgotten'
description:      'The lessons you once learned and already forgot'
url:              ''

# About/contact
author:
  name:           'Nils Moehrle'
  url:            ''

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/nmoehrle/nmoehrle.github.io
